### ISSUE TITLE
[Brainstorming] Roadmap to 1.0

### ISSUE THREAD

**Issue by aojea** [aojea/kindnet#23]
Requirements:

- Minimalistic 
- Opinionated
- Maximize efficiency: performance / resources consumption
- Zero conf
- Reliable

Features:

- [ ] network policies
   -  https://github.com/kubernetes-sigs/kube-network-policies
- [ ] services
   - https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/3866-nftables-proxy/README.md 
- [ ] dns cache
   - https://coredns.io/plugins/cache/ 
- [ ] tunneling
   - only with encryption? vxlan, gneve, LWT tunnels 
- [ ] encryption
   -  https://thermalcircle.de/doku.php?id=blog:linux:nftables_ipsec_packet_flow
   - https://github.com/vishvananda/netlink/blob/main/xfrm_linux.go
   - SPIFFE
   - SDS
- [ ] multiple network interfaces
- [ ] compatibility with other network components: service meshes
- [ ] extensible via plugins
- [ ] zero downtime on upgrades
- [ ] probes
- [ ] xDS

**Comment by aojea** [comment]
I spend the weekend on this, there is no much complex to achieve this goals, but I'm not sure if it is worth it the effort? Is this really what people is looking for?

**Comment by aojea** [comment]
no need for this
